[package]
name = "axon-ibc-light-client"
version = "0.1.0"
authors = ["Nervos Dev <dev@nervos.org>"]
edition = "2021"

[dependencies]
axon-protocol = { git = "https://github.com/axonweb3/axon" }
ibc = "0.20"
ibc-proto = "0.21"
serde = { version = "1.0", features = ["derive"] }
tendermint = "0.25"
